model:
  type: VISION_CLS
  name: resnet20
  params:
    pretrained: True
    num_classes: 10

training:
  criterion: CrossEntropyLoss
  optimizer: Adam
  learning_rate: 0.001
  max_epochs: 500
  val_every_n_epochs: 2
  log_every_n_steps: 10
  callbacks:
    ModelCheckpoint:
      params:
        filename: rniq_checkpoint_rsnt20
    ReduceLrOnOutlier:
      params:
        reduce_scale: 8
    RandNoiseScale:
      params:
        reduce_scale: 2

data:
  dataset_name: CIFAR10
  batch_size: 4000
  num_workers: 20


quantization:
  name: RNIQQuant
  qscheme: 1 # 0 for per-tensor, 1 for per-channel
  act_bit: 21
  weight_bit: 2
  excluded_layers:
    - 'model.module.linear'
    - 'model.module.conv1'
